name: Tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  DEPLOYER_PRIVATE_KEY: 0x0e8ed714e9bf995344fce756e0d93d208ce345bf5ea181a08ee4fe8e4dcf5176

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 18.16.0

      - name: Show repo env secret
        run: |
          echo ${{ env.DEPLOYER_PRIVATE_KEY }}

      - name: Install dependencies
        run: yarn install

      # This is required separately from yarn test because it generates the typechain definitions
      - name: Compile
        run: yarn compile

      - name: Run unit tests
        run: yarn test
